apiVersion: v1
kind: Service
metadata:
  name: mini-web-server-service
spec:
  selector:
    app: mini-web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-web-server
  template:
    metadata:
      labels:
        app: mini-web-server
    spec:
      containers:
      - name: mini-web-server-pod
        image: vvyaches/trvllab:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.2"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
